### ISSUE TITLE
Odd page overflow

### ISSUE THREAD

**Issue by InnocentusLime** [the-Glitchy-Galleon/pirate-jam-15#17]
## Synposis

For some reason the web build has some empty content below the game canvas. That definitely should not be the case

## Todo

- [x] Figure out the cause
- [ ] Fix it

**Comment by hquil** [comment]
proposed fix: in index.html, add the following inside head.
(NOT the body style tag, as that will be removed)
```
	<style>
		body {
			background-color: rgb(25.5, 25.5, 25.5);
			height: 100%;
			margin: 0;
			overflow: hidden;
		}
		canvas {
			position: relative;
			width: 100vw !important;
			height: 100vh !important;
		}
	</style>
```
